### ISSUE TITLE
svg object gets invisible when its root is moved out of the map

### ISSUE THREAD

**Issue by kaynz** [yohanboniface/Leaflet.Editable#32] opened 2015-09-11 14:55 UTC
Hey,

just found a bug, where a path object gets invisible when you move the map so that its root gets out of the visible area of the map.

I've made a video so things get clear pretty fast.

https://www.youtube.com/watch?v=U7SOvKwLHW8&feature=youtu.be

Thanks.

**Comment by yohanboniface** [comment] 2015-09-12 03:43
Sounds bad :/

Which versions of Leaflet and Leaflet.Editable are you using?

**Comment by yohanboniface** [comment] 2015-09-12 05:22
OK, I'm able to reproduce. Will look into this asap. Thanks for the report!

**Comment by yohanboniface** [comment] 2015-09-12 06:07
Should be fixed. Can you try again to confirm? Thanks :)

**Closed** 2015-09-12 06:07 UTC

**Comment by kaynz** [comment] 2015-09-12 07:05
Super fast! Will check this on monday! Thanks

**Comment by kaynz** [comment] 2015-09-14 08:35
Works perfect!

**Comment by yohanboniface** [comment] 2015-09-14 08:39
Cool, thanks for confirmation :)

**Comment by kaynz** [comment] 2015-09-17 09:07
@yohanboniface, hey!

Your fix does not work in ur example:
http://yohanboniface.github.io/Leaflet.Editable/example/snapping.html

Any ideas on this?

**Comment by yohanboniface** [comment] 2015-09-19 08:15
Humm, works for me

**Comment by kaynz** [comment] 2015-09-21 06:49
https://youtu.be/CSDL61XVyl8

**Comment by yohanboniface** [comment] 2015-09-21 12:44
Ah ok, the bug is a bit different :/
Let's open a dedicated issue (I'm doing it).
